title: v1blog
author: v1b3m
email: vibenjamin6@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    My personal blog, I share my thoughts and ideas here.
# social links
twitter_username: BenjaMayanja
github_username: v1b3m

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-dinky

defaults:
    - scope:
          path: 'assets/img'
      values:
          image: true

baseurl: /v1blog
